language: scala

scala:
  - 2.11.12
  - 2.13.0-M4
  - 2.12.6

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

install:
  - pip install --user codecov
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage validateJVM;
  - sbt ++$TRAVIS_SCALA_VERSION benchmark/test coverageReport && codecov;
  - if [[ "$TRAVIS_SCALA_VERSION" == 2.12.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite;
    else echo "Skipping docs on 2.11 and 2.13";
    fi
  - if [[ "$TRAVIS_BRANCH" == "scalajs" ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION clean validateJS;
    else echo "Skipping Scala.js build";
    fi

  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
