dist: xenial
language: scala

scala:
  - 0.22.0-RC1
  - 2.13.0
  - 2.12.10

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

install:
  - pip install --user codecov
  - rvm use 2.6.5 --install --fuzzy
  - yes | gem update --system --force
  - gem install sass
  - gem install jekyll -v 4.0.0

script:
  - if [[ "$TRAVIS_SCALA_VERSION" == 0.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION numbersJVM/test coreJVM/test genericJVM/test jawn/test testsJVM/test;
    else
      sbt ++$TRAVIS_SCALA_VERSION clean coverage validateJVM benchmark/test &&
      sbt ++$TRAVIS_SCALA_VERSION benchmark/test;
    fi
  - if [[ "$TRAVIS_SCALA_VERSION" == 2.12.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite &&
      sbt ++$TRAVIS_SCALA_VERSION coverageReport && codecov;
    else echo "Skipping code coverage reporting and docs on non-2.12 build";
    fi
  - if [[ "$TRAVIS_SCALA_VERSION" == 2.13.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION genericSimpleJVM/test;
    else echo "Skipping generic-simple on non-2.13 build";
    fi
  - if [[ "$TRAVIS_BRANCH" == "scalajs" ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION clean validateJS;
    else echo "Skipping Scala.js build";
    fi

  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
