dist: xenial
language: scala

scala:
  - 2.11.12
  - 2.13.0
  - 2.12.8

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

install:
  - pip install --user codecov
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.8.5

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage validateJVM benchmark/test;
  - sbt ++$TRAVIS_SCALA_VERSION benchmark/test;
  - if [[ "$TRAVIS_SCALA_VERSION" != 2.13.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION coverageReport && codecov;
    else echo "Skipping code coverage reporting on 2.13";
    fi
  - if [[ "$TRAVIS_SCALA_VERSION" == 2.12.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite;
    else echo "Skipping docs on 2.11 and 2.13";
    fi
  - if [[ "$TRAVIS_BRANCH" == "scalajs" ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION clean validateJS;
    else echo "Skipping Scala.js build";
    fi

before_cache:
  # See https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
